version: '3.2'
services:

  wiremock:
    build:
      context: ./config/wiremock
    container_name: 'sda-bootstrap_wiremock'
    ports:
      - 8082:8080
    volumes:
      - ./config/wiremock/stubs/__files:/home/wiremock/__files
      - ./config/wiremock/stubs/mappings:/home/wiremock/mappings
    networks:
      - sda_bootstrap_net

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'sda-bootstrap_rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/sda-bootstrap/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/sda-bootstrap/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - sda_bootstrap_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=root

  postgres:
    image: postgres
    container_name: 'sda-bootstrap_postgres'
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ~/.docker-conf/sda-bootstrap/postgres/data:/var/lib/postgresql/data
    networks:
      - sda_bootstrap_net

  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - sda_bootstrap_net

networks:
  sda_bootstrap_net:
    driver: bridge
